spring:
  application:
    name: BTL_OOP
  datasource:
    password: 24052004
    username: root
    url: 'jdbc:mysql://localhost:3306/btlltw?createDatabaseIfNotExist=true'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  mail:
    username: codeptit123@gmail.com
    password: wnhpagypqhffhwjc
    properties:
      mail: 
        smtp:
          auth: true
          starttls:
            enable: true
    host: smtp.gmail.com
    port: 587
  data:
    redis:
      host: localhost
      port: 6379

vnp:
  tmnCode: 2MKOF115
  hashSecret: SVUDY08SJ9EGOFSQPX3U8DDW276I6ZH4
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: https://ca70-103-238-68-84.ngrok-free.app/api/payment/payment-return
